use_default_settings: true

server:
  secret_key: "CHANGE_ME_generate_a_random_secret"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
  default_theme: simple
  default_locale: en

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json
